program:
  qemu: ./external/qemu/build/qemu-system-x86_64
directories:
  work_dir: ./
  fuzz_inputs: ./fuzz_inputs
  coverage_outputs: ./out/kvm_necofuzz_wo_vmstate_validator
  afl_dir: ./external/AFLplusplus/
  kvm_dir: ./external/linux/arch/x86/kvm
  linux_source_dir: ./external/linux/
  syzkaller_linux_source_dir: ./external/linux_syzkaller/
  xen_dir: ./external/xen/
  xtf_dir: ./external/xtf/
  kvm_unit_tests_dir: ./external/kvm-unit-tests/
fuzzing:
  vcpu_config: 1
  vmstate_validator: 0
  harness: 1
  coverage_guided: 0
  target: kvm
  seed_dir: ./seeds
